#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Marcus Baw / Koloki Ltd
# SPDX-License-Identifier: GPL-3.0-only
# Run the project's JavaScript lint checks.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

exec npm run lint -- "$@"
